package health.keeper;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arifu
 */
public class GeneralHealthPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralHealthPanel
     */
    
    private User user;
    private String datesInStrings[];
    private Day focusedDay;
    private GraphPanel hr;
    private GraphPanel wt;
    
    public GeneralHealthPanel(User user) {
        this.user =user;
        
        initComponents();
        
        //GraphPanel class gets arraylist of doubles only
        hr =new GraphPanel(user.heartRateLog);
        wt = new GraphPanel(user.weightLog);
        this.jTabbedPane1.addTab("Daily resting heart rate", hr);
        this.jTabbedPane1.addTab("Weight Log", wt);

        start();
    }

    //use this method to refresh...
    public void start(){
        //blocking some fuctionality for doctors
        if(!HealthKeeper.isUser()){
            this.jButtonLogDay.setEnabled(false);
            this.jButtonLogHR.setEnabled(false);
            this.jButtonLogDay.setEnabled(false);
            
        }
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            
        datesInStrings=new String[user.days.size()];
        for(int i=0; i<user.days.size();i++){
            datesInStrings[i]=user.days.get(i).date;
        }
        if(datesInStrings.length>0){
            this.jListDays.setListData(datesInStrings);
        }
        else{
            this.jListDays.setListData(new String[]{"empty here"});
        }
        
        
        //setScores function tells the graphpanel to update graph for the data (arrayList of double)
        hr.setScores(user.heartRateLog);
        wt.setScores(user.weightLog);
        
        
        
        this.jLabelGeneralName.setText("Name: "+user.name);
        this.jLabelGeneralAge.setText("Age: "+ user.age);
        this.jLabelGeneralSex.setText("Sex: "+ user.sex);
        this.jLabelGeneralAllergies.setText("Other Info: "+ user.info);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogLogDay = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldActivity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFood = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonSaveDay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCin = new javax.swing.JTextField();
        jTextFieldCout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDays = new javax.swing.JList<>();
        jButtonLogDay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelGeneralName = new javax.swing.JLabel();
        jLabelGeneralAge = new javax.swing.JLabel();
        jLabelGeneralSex = new javax.swing.JLabel();
        jLabelGeneralAllergies = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButtonLogHR = new javax.swing.JButton();
        jButtonLogWeight = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jDialogLogDay.setLocationByPlatform(true);
        jDialogLogDay.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel4.setText("Date:");

        jTextFieldDate.setText("jTextField1");

        jLabel6.setText("Activity details:");

        jTextFieldActivity.setText("jTextField1");

        jLabel7.setText("Food details:");

        jTextFieldFood.setText("jTextField2");

        jLabel8.setText("Calorie intake: ");

        jLabel9.setText("Calorie burnt: ");

        jLabel10.setText("Use a companion mobile application to estimate the total calorie burnt.");

        jButtonSaveDay.setText("Save");
        jButtonSaveDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDayActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Close");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextFieldCin.setText("jTextField1");

        jTextFieldCout.setText("jTextField2");

        javax.swing.GroupLayout jDialogLogDayLayout = new javax.swing.GroupLayout(jDialogLogDay.getContentPane());
        jDialogLogDay.getContentPane().setLayout(jDialogLogDayLayout);
        jDialogLogDayLayout.setHorizontalGroup(
            jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLogDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogLogDayLayout.createSequentialGroup()
                        .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDate)
                            .addComponent(jTextFieldFood)
                            .addComponent(jTextFieldActivity)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLogDayLayout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLogDayLayout.createSequentialGroup()
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSaveDay))))
                    .addGroup(jDialogLogDayLayout.createSequentialGroup()
                        .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCout)
                            .addComponent(jTextFieldCin))))
                .addContainerGap())
        );
        jDialogLogDayLayout.setVerticalGroup(
            jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLogDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jDialogLogDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveDay)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Daily calorie reports:");

        jListDays.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListDays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDaysMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListDays);

        jButtonLogDay.setBackground(new java.awt.Color(153, 204, 255));
        jButtonLogDay.setText("Log another day");
        jButtonLogDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogDayActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei UI", 0, 14))); // NOI18N
        jPanel1.setAutoscrolls(true);

        jLabelGeneralName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabelGeneralName.setForeground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        jLabelGeneralName.setText("name");

        jLabelGeneralAge.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabelGeneralAge.setText("Age");

        jLabelGeneralSex.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabelGeneralSex.setText("Sex:");

        jLabelGeneralAllergies.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabelGeneralAllergies.setText("Allergies:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelGeneralAllergies)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGeneralAge)
                    .addComponent(jLabelGeneralSex)
                    .addComponent(jLabelGeneralName))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelGeneralName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneralAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneralSex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGeneralAllergies))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jButtonLogHR.setBackground(new java.awt.Color(153, 204, 255));
        jButtonLogHR.setText("Log Resting Heart Rate");
        jButtonLogHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogHRActionPerformed(evt);
            }
        });

        jButtonLogWeight.setBackground(new java.awt.Color(153, 204, 255));
        jButtonLogWeight.setText("Log Weight");
        jButtonLogWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                        .addComponent(jButtonLogDay))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogHR)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogHR)
                    .addComponent(jButtonLogWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogDay, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListDaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDaysMouseClicked
        if(datesInStrings.length==0){
            return;
        }
        if (evt.getClickCount() == 2) {
            int focusedIndex = this.jListDays.locationToIndex(evt.getPoint());
            this.focusedDay =user.days.get(focusedIndex);
            resetDialogBoxFor(focusedDay);
            this.jDialogLogDay.setVisible(true);
            
        }
    }//GEN-LAST:event_jListDaysMouseClicked

    private void jButtonSaveDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDayActionPerformed
        String date = this.jTextFieldDate.getText();
        String activity = this.jTextFieldActivity.getText();
        String caloriein = this.jTextFieldCin.getText();
        String caloriout = this.jTextFieldCout.getText();
        String food= this.jTextFieldActivity.getText();
        
        user.days.add(new Day(date,caloriein,food,activity,caloriout));
        
        this.jDialogLogDay.setVisible(false);
        start();
        
    }//GEN-LAST:event_jButtonSaveDayActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.jDialogLogDay.setVisible(false);
        start();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonLogDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogDayActionPerformed
        refreshDialogBox();
        this.jDialogLogDay.setVisible(true);
    }//GEN-LAST:event_jButtonLogDayActionPerformed

    private void jButtonLogHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogHRActionPerformed
        String shr = JOptionPane.showInputDialog(this, "Enter Heart Rate:");
        user.heartRateLog.add(Integer.parseInt(shr)*1.0);
    }//GEN-LAST:event_jButtonLogHRActionPerformed

    private void jButtonLogWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogWeightActionPerformed
        String swt = JOptionPane.showInputDialog(this, "Enter Weight:");
        user.weightLog.add(Integer.parseInt(swt)*1.0);
    }//GEN-LAST:event_jButtonLogWeightActionPerformed

    
    //For some past day
   private void resetDialogBoxFor(Day focusedDay){
       HealthKeeper.centreWindow(this.jDialogLogDay);
       this.jTextFieldDate.setText(focusedDay.date);
       this.jTextFieldDate.setEnabled(false);
       this.jTextFieldActivity.setText(focusedDay.activity);
       this.jTextFieldActivity.setEnabled(false);
       this.jTextFieldFood.setText(focusedDay.foods);
       this.jTextFieldFood.setEnabled(false);
       this.jTextFieldCin.setText(focusedDay.calorieIntake+"");
       this.jTextFieldCin.setEnabled(false);
       this.jTextFieldCout.setText(focusedDay.calorieBurnt+"");
       this.jTextFieldCout.setEnabled(false);
       this.jButtonSaveDay.setEnabled(false);
       
   }
   //makes text fields empty
   private void refreshDialogBox(){
       HealthKeeper.centreWindow(this.jDialogLogDay);
       this.jTextFieldDate.setText("");
       this.jTextFieldDate.setEnabled(true);
       this.jTextFieldActivity.setText("");
       this.jTextFieldActivity.setEnabled(true);
       this.jTextFieldFood.setText("");
       this.jTextFieldFood.setEnabled(true);
       this.jTextFieldCin.setText("");
       this.jTextFieldCin.setEnabled(true);
       this.jTextFieldCout.setText("");
       this.jTextFieldCout.setEnabled(true);
       this.jButtonSaveDay.setEnabled(true);
   }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonLogDay;
    private javax.swing.JButton jButtonLogHR;
    private javax.swing.JButton jButtonLogWeight;
    private javax.swing.JButton jButtonSaveDay;
    private javax.swing.JDialog jDialogLogDay;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGeneralAge;
    private javax.swing.JLabel jLabelGeneralAllergies;
    private javax.swing.JLabel jLabelGeneralName;
    private javax.swing.JLabel jLabelGeneralSex;
    private javax.swing.JList<String> jListDays;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldActivity;
    private javax.swing.JTextField jTextFieldCin;
    private javax.swing.JTextField jTextFieldCout;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldFood;
    // End of variables declaration//GEN-END:variables
}
