/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health.keeper;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;


public class MedicinesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicinesPanel
     */
    
    List<Medicine> suggestedMedicines;
    List<Medicine> previousMedicines;
    String[] namesOfSuggested;
    String[] namesOfPrevious;
    User user;
    Medicine focusedMedicine;

    public MedicinesPanel(User user) {
        initComponents();
        HealthKeeper.centreWindow(this.jDialogMedicineData);
        HealthKeeper.centreWindow(this.jDialogSuggestMedicine);
        this.user=user;
        start();
    }
    
    
    
    
    public void start(){
        
        this.suggestedMedicines=new ArrayList<Medicine>();
        this.previousMedicines=new ArrayList<Medicine>();
        
        for(int i=0; i<user.medicines.size();i++){
            if(user.medicines.get(i).isSuggested){
                this.suggestedMedicines.add(user.medicines.get(i));
            }
            else{
                this.previousMedicines.add(user.medicines.get(i));
            }
        }
        
        this.namesOfSuggested = new String[this.suggestedMedicines.size()];
        this.namesOfPrevious = new String[this.previousMedicines.size()];
        
        
        System.out.println(namesOfSuggested.length+"   "+namesOfPrevious.length);
        for(int i=0; i<this.suggestedMedicines.size();i++){
            this.namesOfSuggested[i] = this.suggestedMedicines.get(i).name;
        }
        for(int i=0; i<this.previousMedicines.size();i++){
            if(previousMedicines.get(i).isForbidden){
                this.namesOfPrevious[i] = "(Forbidden) "+this.previousMedicines.get(i).name;
            }
            else{
                this.namesOfPrevious[i] = this.previousMedicines.get(i).name;
            }
        }
        
        if(namesOfPrevious.length>0){
            this.jListPrevious.setListData(namesOfPrevious);
        }
        else{
            this.jListPrevious.setListData(new String[]{"empty here"});
        }
        
        if(namesOfSuggested.length>0){
            this.jListNewMedicines.setListData(namesOfSuggested);
        }
        else{
            this.jListNewMedicines.setListData(new String[]{"empty here"});
        }
        
        
        
        
        if(HealthKeeper.isUser()){
            this.jButtonSuggestMedicine.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMedicineData = new javax.swing.JDialog();
        jLabelMedicineName = new javax.swing.JLabel();
        jLabelStartDate = new javax.swing.JLabel();
        jLabelSuggestedBy = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelComment = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jButtonForbid = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCommentPrevious = new javax.swing.JTextArea();
        jDialogSuggestMedicine = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMedicineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerQuantityPerDay = new javax.swing.JSpinner();
        jComboBoxUnit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddComment = new javax.swing.JTextArea();
        jButtonSaveSuggestion = new javax.swing.JButton();
        jButtonCancelSuggestion = new javax.swing.JButton();
        jSpinnerDuration = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListNewMedicines = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonSuggestMedicine = new javax.swing.JButton();
        jButtonMedicalShopReport = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPrevious = new javax.swing.JList<>();

        jDialogMedicineData.setAlwaysOnTop(true);
        jDialogMedicineData.setIconImage(null);
        jDialogMedicineData.setLocationByPlatform(true);
        jDialogMedicineData.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabelMedicineName.setText("Medicine Name:");

        jLabelStartDate.setText("Start Date");

        jLabelSuggestedBy.setText("Suggested By:");

        jLabelQuantity.setText("Quantity Per Day:");

        jLabelComment.setText("Comment By the Doctor:");

        jLabelDuration.setText("Duration:");

        jButtonForbid.setText("Avoid this Medicine");
        jButtonForbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForbidActionPerformed(evt);
            }
        });

        jTextAreaCommentPrevious.setColumns(20);
        jTextAreaCommentPrevious.setRows(5);
        jScrollPane4.setViewportView(jTextAreaCommentPrevious);

        javax.swing.GroupLayout jDialogMedicineDataLayout = new javax.swing.GroupLayout(jDialogMedicineData.getContentPane());
        jDialogMedicineData.getContentPane().setLayout(jDialogMedicineDataLayout);
        jDialogMedicineDataLayout.setHorizontalGroup(
            jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMedicineDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jDialogMedicineDataLayout.createSequentialGroup()
                        .addGroup(jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMedicineName)
                            .addComponent(jLabelStartDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jButtonForbid))
                    .addGroup(jDialogMedicineDataLayout.createSequentialGroup()
                        .addGroup(jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSuggestedBy)
                            .addComponent(jLabelQuantity)
                            .addComponent(jLabelComment)
                            .addComponent(jLabelDuration))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogMedicineDataLayout.setVerticalGroup(
            jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMedicineDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogMedicineDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogMedicineDataLayout.createSequentialGroup()
                        .addComponent(jLabelMedicineName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelStartDate))
                    .addComponent(jButtonForbid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSuggestedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelComment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogSuggestMedicine.setAlwaysOnTop(true);
        jDialogSuggestMedicine.setLocationByPlatform(true);
        jDialogSuggestMedicine.setMinimumSize(new java.awt.Dimension(500, 400));

        jLabel3.setText("Medicine Name:");

        jTextFieldMedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMedicineNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Duration: ");

        jLabel5.setText("Quantity per day");

        jComboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet/s", "ml/s" }));
        jComboBoxUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitActionPerformed(evt);
            }
        });

        jLabel6.setText("Comments:");

        jTextAreaAddComment.setColumns(20);
        jTextAreaAddComment.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddComment);

        jButtonSaveSuggestion.setText("Save");
        jButtonSaveSuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSuggestionActionPerformed(evt);
            }
        });

        jButtonCancelSuggestion.setText("Cancel");
        jButtonCancelSuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelSuggestionActionPerformed(evt);
            }
        });

        jLabel7.setText("days");

        javax.swing.GroupLayout jDialogSuggestMedicineLayout = new javax.swing.GroupLayout(jDialogSuggestMedicine.getContentPane());
        jDialogSuggestMedicine.getContentPane().setLayout(jDialogSuggestMedicineLayout);
        jDialogSuggestMedicineLayout.setHorizontalGroup(
            jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSuggestMedicineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSuggestMedicineLayout.createSequentialGroup()
                        .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldMedicineName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSuggestMedicineLayout.createSequentialGroup()
                        .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerDuration, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerQuantityPerDay, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSuggestMedicineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelSuggestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSaveSuggestion)
                .addContainerGap())
        );
        jDialogSuggestMedicineLayout.setVerticalGroup(
            jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSuggestMedicineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerQuantityPerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jDialogSuggestMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveSuggestion)
                    .addComponent(jButtonCancelSuggestion))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CURRENT MEDICINES:");

        jListNewMedicines.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jListNewMedicines.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListNewMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListNewMedicinesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListNewMedicines);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("TO BUY:");

        jButtonSuggestMedicine.setBackground(new java.awt.Color(153, 204, 255));
        jButtonSuggestMedicine.setText("Prescribe Medicine");
        jButtonSuggestMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuggestMedicineActionPerformed(evt);
            }
        });

        jButtonMedicalShopReport.setBackground(new java.awt.Color(153, 204, 255));
        jButtonMedicalShopReport.setText("Medical Shop Report");
        jButtonMedicalShopReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicalShopReportActionPerformed(evt);
            }
        });

        jListPrevious.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jListPrevious.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPreviousMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListPrevious);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonSuggestMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMedicalShopReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuggestMedicine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMedicalShopReport)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSuggestMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuggestMedicineActionPerformed
        this.jDialogSuggestMedicine.setVisible(true);
    }//GEN-LAST:event_jButtonSuggestMedicineActionPerformed

    private void jComboBoxUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitActionPerformed

    private void jTextFieldMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMedicineNameActionPerformed

    private void jListNewMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListNewMedicinesMouseClicked
        if(namesOfSuggested.length==0){
            return;
        }
        if (evt.getClickCount() == 2) {
            int focusedIndex = this.jListNewMedicines.locationToIndex(evt.getPoint());
            this.focusedMedicine =this.suggestedMedicines.get(focusedIndex);
            refreshMedicineDataDialogFor(focusedMedicine);

            this.jDialogMedicineData.setVisible(true);
            
        }
    }//GEN-LAST:event_jListNewMedicinesMouseClicked

    private void jButtonSaveSuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSuggestionActionPerformed
        
        String comment= this.jTextAreaAddComment.getText();
        String name=this.jTextFieldMedicineName.getText();
        int duration=(int)this.jSpinnerDuration.getValue();
        int quantity=(int)this.jSpinnerQuantityPerDay.getValue();
        String type=this.jComboBoxUnit.getSelectedItem().toString();

        System.out.println(comment+name+duration+quantity+type);
        Doctor doc =HealthKeeper.getCurrentDoctor();
        Medicine temp = new Medicine(name,duration,comment, quantity, doc,type);
        user.medicines.add(temp);
        this.jDialogSuggestMedicine.setVisible(false);
        refreshSuggestMedicineDialog();
        start();
    }//GEN-LAST:event_jButtonSaveSuggestionActionPerformed

    private void jButtonCancelSuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelSuggestionActionPerformed
        this.jDialogSuggestMedicine.setVisible(false);
        refreshSuggestMedicineDialog();
        start();
    }//GEN-LAST:event_jButtonCancelSuggestionActionPerformed

    private void jButtonMedicalShopReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicalShopReportActionPerformed
        
        
        String bill="NOTE: ENTER YES WHEN YOU BUY THE MEDICINES\n";
        for(int i=0;i<this.suggestedMedicines.size();i++){
            String name =this.suggestedMedicines.get(i).name;
            int totalQuantity=this.suggestedMedicines.get(i).quatitityPerDay*this.suggestedMedicines.get(i).duration;
            bill+=totalQuantity+ " "+ this.suggestedMedicines.get(i).type+" of "+name+"\n";
        }
        
        
        
        int confirmed = JOptionPane.showConfirmDialog(null,
                bill, "Medical Shop Bill",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            for(int i=0; i<this.suggestedMedicines.size();i++){
                this.suggestedMedicines.get(i).isSuggested=false;
                this.previousMedicines.add(this.suggestedMedicines.get(i));
                this.suggestedMedicines.get(i).startDate=new Date();
                this.suggestedMedicines.remove(i);
            }
        }
       start();
    }//GEN-LAST:event_jButtonMedicalShopReportActionPerformed

    private void jListPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPreviousMouseClicked
        if(namesOfPrevious.length==0){
            return;
        }
        if (evt.getClickCount() == 2) {
            int focusedIndex = this.jListPrevious.locationToIndex(evt.getPoint());
            this.focusedMedicine =this.previousMedicines.get(focusedIndex);
            refreshMedicineDataDialogFor(focusedMedicine);

            this.jDialogMedicineData.setVisible(true);
            
        }
    }//GEN-LAST:event_jListPreviousMouseClicked

    
    
    //make the medicince forbidden by setting the forbidden field as true
    private void jButtonForbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForbidActionPerformed
        this.jDialogMedicineData.setAlwaysOnTop(false);
        int confirmed = JOptionPane.showConfirmDialog(null,
                "This is irreversible, do you still want to continue?", "Confirm?",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            this.focusedMedicine.isForbidden=true;
            this.focusedMedicine.isSuggested=false;
        }
        
        
        
        start();
        this.refreshMedicineDataDialogFor(focusedMedicine);
        this.jDialogMedicineData.setAlwaysOnTop(true);
    }//GEN-LAST:event_jButtonForbidActionPerformed


    
    //update jlabels and stuff to display info of medicine....
    public void refreshMedicineDataDialogFor(Medicine medicine){
        HealthKeeper.centreWindow(this.jDialogMedicineData);
        this.jLabelMedicineName.setText("Medicine Name: "+medicine.name);
        
        if(medicine.isSuggested){
            this.jLabelStartDate.setText("Start Date: ----haven't started yet----");
        }
        else{
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            this.jLabelStartDate.setText("Start Date: "+dateFormat.format(new Date()));
        }
        
        this.jLabelSuggestedBy.setText("Prescribed By: "+medicine.suggestedBy.getName());
        this.jLabelQuantity.setText("Quantity: "+ medicine.quatitityPerDay+medicine.type+" per day");
        this.jLabelDuration.setText("Duration: "+medicine.duration +" days");
        this.jTextAreaCommentPrevious.setText(medicine.comment);
        this.jTextAreaCommentPrevious.setEnabled(false);
        if(medicine.isForbidden){
            this.jButtonForbid.setEnabled(false);
            this.jButtonForbid.setText("Forbidden now...");
        }
        else{
            this.jButtonForbid.setEnabled(true);
            this.jButtonForbid.setText("Forbid now");
        }
    }
    
    public void refreshSuggestMedicineDialog(){
        this.jTextFieldMedicineName.setText("");
        this.jTextAreaAddComment.setText("");
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelSuggestion;
    private javax.swing.JButton jButtonForbid;
    private javax.swing.JButton jButtonMedicalShopReport;
    private javax.swing.JButton jButtonSaveSuggestion;
    private javax.swing.JButton jButtonSuggestMedicine;
    private javax.swing.JComboBox<String> jComboBoxUnit;
    private javax.swing.JDialog jDialogMedicineData;
    private javax.swing.JDialog jDialogSuggestMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelComment;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelMedicineName;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStartDate;
    private javax.swing.JLabel jLabelSuggestedBy;
    private javax.swing.JList<String> jListNewMedicines;
    private javax.swing.JList<String> jListPrevious;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinnerDuration;
    private javax.swing.JSpinner jSpinnerQuantityPerDay;
    private javax.swing.JTextArea jTextAreaAddComment;
    private javax.swing.JTextArea jTextAreaCommentPrevious;
    private javax.swing.JTextField jTextFieldMedicineName;
    // End of variables declaration//GEN-END:variables
}
